name: hacked-2019
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - selenium
  - feedparser
  - requests
  - tqdm
  - flask
  - flask-restful
  - flask-cors
  - nltk
  - pandas
  - beautifulsoup4